buckaroo-it/Magento2

composer.json

`facebook/webdriver` has been deprecated and renamed to [php-webdriver/webdriver](https://packagist.org/packages/php-webdriver/webdriver), see https://github.com/php-webdriver/php-webdriver#upgrade-from-version-180
This is just drop-in replacement.

Replace deprecated facebook/webdriver with php-webdriver

---

Model/Method/Afterpay20.php

When trying to refund an order with zero tax percentage order line, Buckaroo it's building an empty XML tag which is causing an error.
This PR just fixes how Buckaroo treats this value, checking if it's null and placing a zero as value.

[BP-1223] Buckaroo was sending an empty XML tag when trying to process a null tax percentage

---

Model/Push.php

This pull request fixes the issue described on https://github.com/buckaroo-it/Magento2/issues/576.
Two or more partial refunds of the same order that needs approval don't create all necessary creditmemos when approved at the same time (batch approval).
The problem starts at the `handleAwaitingApprovalRefunds` method, which handles the status **BUCKAROO_MAGENTO2_STATUSCODE_PENDING_APPROVAL** from a refund when the customer attempts to create a creditmemo and receives the awaiting approval message.
Inside this method, if conditions are met, it calls **setReceivedTransactionStatuses** which inside has the following validation:
```
if (!$payment->getAdditionalInformation(self::BUCKAROO_RECEIVED_TRANSACTIONS_STATUSES)) {
$payment->setAdditionalInformation( …
```

2+ partial refunds of the same order doesn't generate credit memo for all refunds when approved at the same time

---

Model/Service/CreateInvoice.php
Observer/SetTransactionOnInvoiceObserver.php
etc/di.xml
etc/events.xml

BP-2865 - Creating an invoice using the 'Invoice' doesn't create capture transaction
The transaction is not created when the invoice is made using the invoice button, which results in only the offline refund

BP-2865 - Creating an invoice using the 'Invoice' doesn't create capture

---

Model/Push.php

the 791 status is not processed at all when the payment method is PayConiq

BP-2940 - Payconiq orders are sometimes getting "Cancelled" when the payment is succesfull

---

Block/Adminhtml/Config/Support/SupportTab.php
Test/Unit/Block/Adminhtml/Config/Support/SupportTabTest.php

When this module is run under Mage-OS 1.0, the current code gives a Fatal Error due to an unmatched array key. Actually, any version that is not in the array, throws this error. This PR fixes this, with the idea to support Mage-OS.

Add support for Mage-OS 1.0.x

---

Controller/Applepay/SaveOrder.php
Model/Service/QuoteAddressService.php

Changed the billing address to get the phone from the shipping address if the billing phone is missing

BP-3516 Apple Pay phone number is only added to the shipping address

---

Model/Method/AbstractMethod.php

fix error "Action" key doesn't exist

BP-3677-Some-payment-methods-are-not-working-error

---

Model/Push.php

fix order not updated to processing

BP-3627-Order-placed-with-Bank-transfer-remains-pending-state-when-create-invoice-on-shipment-is-active

---

Helper/Data.php
Model/Method/Billink.php
view/frontend/web/js/view/payment/method-renderer/billink.js
view/frontend/web/template/payment/buckaroo_magento2_billink.html

fix billink always B2B, and remove billing name from front

BP-3678-Billink-is-always-B2B

---

Test/BaseTest.php

This PR removes the check for a `functions.php` file which is not needed in Magento 2. Unit tests should be run similarly like `vendor/bin/phpunit --configuration dev/tests/unit/phpunit.xml.dist vendor/buckaroo/magento2/Test/Unit`. This way, the PHP settings should also be moved to the PHPUnit configuration file and not be part of the tests.

Remove unneeded code in tests

---

Test/BaseTest.php

This PR makes sure that the `setUp` method of all relevant tests is compatible with up-to-date PHPUnit versions (8 and up) as included in Magento 2.4.+

Make BaseTest compatible with newer PHPUnit versions

---

Test/BaseTest.php

Create a mock for the `assertInternalType` method which is removed from PHPUnit. See also https://github.com/sebastianbergmann/phpunit/issues/3369

Method assertInternalType is deprecated

---

Model/Total/Quote/BuckarooFee.php
Model/Total/Quote/BuckarooFeeHyva.php
Service/HyvaCheckoutConfig.php

check if hyva checkout is active

BP-3761-Adjustment-in-the-main-module-to-resolve-an-issue-with-giftcards-for-the-additional-Hyv-Checkout-module

---

Gateway/Request/BasicParameter/ClientIPDataBuilder.php
Model/Service/Order.php
Ui/Component/Listing/Column/Method/Filter.php
Ui/Component/Listing/Column/Method/Options.php

BP-3701-Change-Zend-to-Laminas

---

Service/Formatter/Address/PhoneFormatter.php
Service/Formatter/AddressFormatter.php

fix phone number required and also refactor the file

BP-3915-Klarna-KP-transaction-fails-when-Phone-number-field-is-not-enabled-in-checkout

---

Model/Ideal/QuoteCreate.php

BP-3896-Product-link-in-cart-becomes-Invalid-after-canceling-iDEAL-quick-checkout-causing-404-error-on-frontend

---

Helper/PaymentFee.php
Model/ConfigProvider/BuckarooFee.php
Model/Method/AbstractMethod.php
Model/Method/Afterpay.php
Model/Total/Quote/Tax/BuckarooFee.php
Model/Total/Quote/Tax/BuckarooFeeAfterTax.php
Service/Sales/Pdf/BuckarooFee.php
Service/Tax/TaxCalculate.php
Test/Unit/Model/Total/Quote/BuckarooFeeTest.php

BP-4026-Payment-Fee-Tax-Class-None-still-has-a-VAT-percentage-for-Riverty-Billink-Klarna

---

Model/ConfigProvider/Account.php
Model/Ideal/QuoteBuilder.php
Service/Sales/Quote/Recreate.php
view/frontend/templates/catalog/product/view/ideal-fast-checkout.phtml
view/frontend/templates/checkout/cart/ideal-fast-checkout.phtml

ideal-fast-checkout keep cart alive from product page

BP-4108-Cart-Alive-works-on-shopping-cart-but-not-on-product-page

---

Model/Total/Quote/BuckarooRemainingAmount.php

dont return remaining amount if no partial payment is done

BP-4177-Remaining-amount-is-always-showing-in-the-checkout

---

view/frontend/web/js/view/checkout/applepay/pay.js
view/frontend/web/js/view/payment/method-renderer/applepay.js

refactor applepay: update method to check Apple Pay support and impreve visibility logic

BP-4217-Apple-Pay-should-not-be-visible-in-the-checkout-on-non-Apple-devices

---

Model/Method/Trustly.php

To fix the error Parameter 'ConsumerEmail' is missing when using the Trustly payment method. See #1200

BP-4269 Add ConsumerEmail to request parameters

---

Api/PaypalExpressOrderCreateInterface.php
Block/Adminhtml/Sales/Order/Creditmemo/Create/BankFields.php
Block/Catalog/Product/View/Applepay.php
Block/Catalog/Product/View/IdealFastCheckout.php
Block/Catalog/Product/View/PaypalExpress.php
Gateway/Command/GatewayCommand.php
Gateway/Request/Recipient/AfterpayOldDataBuilder.php
Helper/Data.php
Model/Adapter/BuckarooAdapter.php
Model/Config/Backend/AllowedCurrencies.php
Model/Config/Backend/TransactionLabel.php
Model/Config/Source/AllowedCountries.php
Model/Config/Source/AllowedCurrencies.php
Model/ConfigProvider/AbstractConfigProvider.php
Model/ConfigProvider/Account.php
Model/ConfigProvider/Idin.php
Model/ConfigProvider/Method/PayPerEmail.php
Model/Giftcard/Api/GetTransactionsResponse.php
Model/Method/BuckarooAdapter.php
Model/Order/CreditmemoFactory.php
Model/PaypalExpress/OrderCreate.php
Model/PaypalExpress/QuoteCreate.php
Model/PaypalStateCodes.php
Model/Push/DefaultProcessor.php
Model/Total/Quote/Tax/BuckarooFee.php
Plugin/CartManagement.php
Plugin/FixSession.php
Plugin/GuestSaveManager.php
Service/PayReminderService.php

add nullable type hints for various parameters across multiple classes to improve code clarity and compatibility with PHP 8.4

BP-4230-Add-support-for-PHP-8.4

---

view/frontend/web/js/view/payment/method-renderer/billink.js

update: fix billing name display for Billink payment method by ensuring company name is shown if available

P-4431-Billing-name-showing-as-blank-for-Billink-payment-method

---

Helper/Data.php

Customer group was throwing an error when any type was selected because it returns a string but the method return type was set to int.

fix: update return type of determineCustomerGroup method to string

---

Gateway/Validator/IssuerValidator.php

refactor: simplify payment information retrieval in IssuerValidator

BP-4579-Order-fails-with-PayByBank-Error-Payment-data-object-should-be-provided

---

etc/adminhtml/system/payment_methods/billink.xml

update: remove Consumer Financial Warning setting from Billink configuration

Bp 4926 two consumer financial warning settings showing for billink on the configuration tab
