buckaroo-it/Magento2

Model/Method/AbstractMethod.php
Model/Method/Capayable.php
Model/Method/Creditcards.php
Model/Method/Emandate.php
Model/Method/Giftcards.php
Model/Method/Klarnakp.php
Model/Method/PayLink.php
Model/Method/PayPerEmail.php
Model/Method/SepaDirectDebit.php
Model/Method/Transfer.php
etc/di.xml

BP-826 AbstractMethod Buckaroo Logger to be loaded via di, not by using the object manager.

BP-826 AbstractMethod Buckaroo Logger to be loaded via di, not object

---

view/frontend/email/second_chance.html
view/frontend/email/second_chance2.html

getUrl closing sq bracket

---

Model/ConfigProvider/Method/Creditcards.php

Fixed creditcards error in checkout.

Feature/bp 1047 fix 2.0 issues

---

Logging/Log.php

Adding missing addDebug function

---

Logging/Log.php

Updating addRecord function to match interface

---

README.md

Added a index to the readme file (README.md)

Added a index to README.md

---

CONTRIBUTING.md

Some small textual changes (typo).

Update CONTRIBUTING.md (small textual changes)

---

Model/Push.php

Also this ticket it is fixed by this commit:
https://jira.buckaroo.nl/browse/BP-1998

Bp 2013 refund issue klarna kp

---

Api/TransactionResponseInterface.php
Gateway/Http/Client/Json.php
Gateway/Http/TransactionBuilder/AbstractTransactionBuilder.php
Model/Transaction/Status/ProcessResponse.php
Model/Transaction/Status/Response.php
etc/di.xml

required for GraphQl to work: https://github.com/buckaroo-it/Magento2_GraphQL/pull/9

Retrieve transaction status from payment engine

---

README.md

**Update README.md versions change and extra notice.**
- Removed "or higher" for the Magento version.
- Removed "or higher" for the PHP version.
- Added a notice: This file has been prepared with the greatest possible care and is subject to language and/or spelling errors.

Update README.md versions change and extra notice.

---

i18n/de_DE.csv
i18n/fr_FR.csv
i18n/nl_NL.csv

Fix incorrect translation

---

README.md

We've added the Hyvä React checkout module to the main Magento 2 README file.
This since we are going to release this extension soon.

Update README.md Hyvä React checkout module added

---

Model/Push.php

If Transaction is part of Group Transaction don't change the order status from canceled to processing

BP-2184 partially paid group transaction

---

Model/Service/Order.php
Observer/RestoreQuote.php

BP-2182 Can-not-cancel-order-with-klarnakp after press back button

---

README.md

We've updated the README with links to our new support page.

Update README.md support links.

---

i18n/de_DE.csv

Update de-DE.csv change tooltip translation, to make the option more clear.

BP-2250 Change de-DE tooltip translation (Display only for selected IPs)

---

i18n/nl_NL.csv

Update nl-NL.csv change tooltip translation, to make the option more clear.

BP-2249 Change nl-NL tooltip translation (Display only for selected IPs)

---

Model/ConfigProvider/Method/AbstractConfigProvider.php
Model/Method/AbstractMethod.php
Model/PaymentInformationManagement.php

BP-2220 - In3-applicable-countries-not-working

---

Observer/AddInTestModeMessage.php

BP-2430 - Change the type of the messages AddInTestModeMessage

BP-2431 - Throw an error if the order is not found

---

Model/Adapter/BuckarooAdapter.php
README.md
Service/Software/Data.php
composer.json

Buckaroo Refactor - Add Platform and Module details on Buckaroo SDK request

Buckaroo Refactor - Add Platform and Module details on Buckaroo SDK request

---

Plugin/GuestSaveManager.php

BP-2867 Fatal Error: with OneStepCheckout in GuestSaveManager.php #758

---

Controller/Adminhtml/PayLink/Index.php
Controller/Checkout/Idin.php
Gateway/Http/Bpe3.php
Model/Method/AbstractMethod.php

https://buckaroonl.atlassian.net/browse/BP-2799
Bug with mode is set to '0'

Hotfix - Buckaroo transaction when 'mode' is not set or set to 0.

---

Model/Method/Capayable/In3V3Builder.php

Send only two decimals (without rounding) in plaza

BP-3100-ideal-in3-rounding-issue-3decimals

---

README.md

We've updated the README file with some more white spaces for better readability. Also the "In development" notice for the Hyvä Checkout module is removed, since that has been released now.

BP-3158 Update README.md

---

view/adminhtml/templates/supportTab.phtml

BP-3341 add buckaroo hyva checkout module to the additional plugins list

---

Model/Method/Billink.php

BP-3306 billink vat percentage for discounts

---

Model/Push.php

BP-3412 refund approval workflow not working for transfer and giftcards

---

README.md
Service/Software/Data.php
composer.json
etc/module.xml

BP-3537-Update-test-release-v1.49.0

---

view/adminhtml/templates/supportTab.phtml

update supported magento version

Bp 3537 update test release v1.49.0

---

Model/Method/SepaDirectDebit.php
Test/Unit/Model/Method/SepaDirectDebitTest.php

fix SepaDirectDebit replace nonexistent package

Bp 3683 sepa direct debit transaction shows error an error occurred on the server please try again

---

Test/Unit/Model/Validator/PushTest.php

The filename `PushTest` should match the classname `PayPerEmailTest` (or vice versa)

Filename does not match class

---

Controller/Redirect/Process.php
Observer/RestoreQuote.php
Service/Sales/Quote/Recreate.php
Test/Unit/Service/Sales/Quote/RecreateTest.php

keep products in the cart but delete address if its idealfastcheckout

BP-3755-iDEAL-fast-checkout-shopping-cart-should-not-be-empty-after-cancellation-go-back

---

Model/Method/Giropay.php

change channel for giropay to Web

BP-3775-Giropay-does-not-refund-on-backend

---

Service/Software/Data.php
composer.json
etc/module.xml

BP-3754-Update-test-release-1.50.0

---

Model/Total/Quote/BuckarooFeeHyva.php

remove setGrandTotal in BuckarooFeeHyva.php

BP-3739-Improve-Buckaroo-fee-handling

---

Model/Total/Quote/BuckarooAlreadyPay.php
view/frontend/layout/checkout_index_index.xml
view/frontend/web/js/action/place-order.js
view/frontend/web/js/view/checkout/summary/grand-total.js

replace already paid collect function with grand-total also fix full payment with giftcard

BP-3778-The-transaction-calculations-are-not-being-compiled-properly

---

Service/Software/Data.php
composer.json
etc/module.xml

Update, test & release (1.50.1)

BP-3780-Update-test-release-1.50.1

---

view/frontend/layout/catalog_product_view.xml
view/frontend/layout/checkout_cart_index.xml
view/frontend/templates/catalog/product/view/ideal-fast-checkout.phtml
view/frontend/templates/checkout/cart/ideal-fast-checkout.phtml
view/frontend/web/css/ideal-fast-checkout.css
view/frontend/web/js/view/checkout/ideal-fast-checkout/pay.js

I have refactored the implementation of the "Fast Checkout iDEAL" button on the product page. The goal is to replace the previous jQuery-based implementation with Magento's native Knockout.js and UI component system, improving maintainability and future compatibility with Magento upgrades.

BP-3838-Refactor-Fast-Checkout-Button-Implementation-for-iDEAL-using-Magento-UI-Components

---

Api/Data/QuoteCreateResponseInterface.php
Api/IdealQuoteCreateInterface.php
Api/PayWithGiftcardInterface.php
Api/PaypalExpressQuoteCreateInterface.php

BP-3843-v1.50-breaks-Magento-API-schema

---

Controller/Redirect/Process.php
Model/Push.php

update ideal fast checkout email sender

BP-3826-iDEAL-Fast-Checkout-Dummy-Data-still-visible-after-cancellation

---

etc/csp_whitelist.xml

add csp_whitelist for applePay and Payconiq

BP-3856-Add-CSP-allow-list-for-Apple-Pay-Payconiq

---

Block/Widget/Button/Toolbar.php
Helper/Data.php
Model/Config/Source/PaymentMethods/AfterExpiry.php
Model/Config/Source/PaymentMethods/PayLink.php
Model/Config/Source/PaymentMethods/PayPerEmail.php
Model/ConfigProvider/Method/Giropay.php
Model/Method/Giropay.php
Model/Service/Order.php
Test/Unit/Model/Config/Source/PaymentMethods/AfterExpiryTest.php
Test/Unit/Model/Config/Source/PaymentMethods/PayPerEmailTest.php
Test/Unit/Model/ConfigProvider/Method/GiropayTest.php
Test/Unit/Model/Method/GiropayTest.php
etc/adminhtml/system/payment_methods.xml
etc/adminhtml/system/payment_methods/giropay.xml
etc/config.xml
etc/di.xml
etc/frontend/di.xml
etc/payment.xml
i18n/de_DE.csv
i18n/es_ES.csv
i18n/fr_FR.csv
i18n/nl_BE.csv
i18n/nl_NL.csv
view/frontend/layout/checkout_index_index.xml
view/frontend/web/css/styles.css
view/frontend/web/js/view/payment/buckaroo-payments.js
view/frontend/web/js/view/payment/method-renderer/giftcards.js
view/frontend/web/js/view/payment/method-renderer/giropay.js
view/frontend/web/template/payment/buckaroo_magento2_giropay.html

Reverts buckaroo-it/Magento2#1087

Revert "get hotfix changes"

---

Model/ConfigProvider/Method/Applepay.php

BP-3894-Fix-An-error-has-happened-during-application-run-Apple-Pay

---

Controller/Redirect/Process.php

BP-3904-Check-provided-Magento-2-error-log-from-specific-merchant

---

Gateway/Http/TransactionBuilder/Refund.php
Gateway/Http/TransactionBuilder/RefundPartial.php

add status closed when refunded

BP-3986-iDeal-does-not-update-the-status-correctly

---

Model/Push.php

check invoice handling for store configs

BP-3830-Paylink-order-from-secondary-store-view-is-not-updated-to-processing

---

view/frontend/web/js/view/summary/totals.js

BP-4009-buckarooFee.title-is-not-a-function

---

Observer/HtmlTransactionIdObserver.php

BP-4099-Klarna-KP-link-to-transaction-instead-of-datarequest

---

view/frontend/web/css/styles.css

update paybybank issuer images

BP-4113-PayByBank-issuer-images-not-loading

---

Model/Method/Eps.php

Reverts buckaroo-it/Magento2#1143

Revert "BP-4145  Invoice is not automatically created for EPS"

---

Service/Software/Data.php
composer.json
etc/module.xml

BP-3982-Update-Test-Release-1.51.0

---

view/frontend/templates/checkout/cart/applepay.phtml
view/frontend/web/js/view/checkout/applepay/catalog-cart-view.js

BP-4146-Don-t-require-CSP-if-it-is-disabled

---

Model/Service/Order.php

change Expression to Zend_Db_Expr

BP-4168-Cron-job-error-buckaroo_magento2_cancel_cron

---

Model/Service/Order.php

refactor Order: update order state and status handling to include status history comments

BP-4207-Klarna-KP-push-does-not-update-a-pending-order-to-cancelled

---

Setup/UpgradeData.php
etc/adminhtml/system/payment_methods/knaken.xml
etc/config.xml

refactor: rename Knaken Settle to goSettle in configuration and upgrade script

BP-4024-Rebranding-Knaken-Settle-into-goSettle-Magento-2

---

Setup/Patch/Data/UpdateKnakenTitleToGoSettle.php
etc/config.xml
i18n/nl_NL.csv

Add data patch to update Knaken payment method title to goSettle

Bp 4025 rebranding knaken settle into go settle magento 2 refactor

---

view/frontend/web/js/view/payment/method-renderer/creditcards.js
view/frontend/web/template/payment/buckaroo_magento2_creditcards.html

refactor credit card handling: move OAuth token retrieval to initCreditCardFields method

BP-3912-Improve-default-Hosted-Fields-design

---

Plugin/CheckoutManagement.php
Plugin/GuestSaveManager.php
etc/di.xml

refactor checkout management: enhance item quantity update and payment information handling

BP-4295-Add-support-for-Magento-2.4.8

---

view/frontend/web/template/payment/buckaroo_magento2_klarna.html
view/frontend/web/template/payment/buckaroo_magento2_klarnain.html
view/frontend/web/template/payment/buckaroo_magento2_klarnakp.html

refactor payment warnings: update financial warning text to include links to terms and privacy policy

BP-4285-Terms-and-Conditions-hyperlink-adjustments-for-Klarna

---

Service/Software/Data.php
composer.json
etc/module.xml

bump version to 1.52.0 in composer.json, Data.php, and module.xml

BP-3682-Update-test-release-v1.52.0

---

etc/di.xml

fix: Remove global issuer validator from di.xml configuration

BP-4330-Fix-Ideal-asking-for-issuers

---

Model/Service/Order.php
Ui/Component/Listing/Column/Method/Filter.php
Ui/Component/Listing/Column/Method/Options.php

update: replace Zend_Db_Expr with Magento\Framework\DB\Sql\Expression…in Filter, Options, and Order classes

BP-3701-Change-Zend-to-Laminas

---

Gateway/Request/Capayable/ArticlesDataBuilder.php

update: optimize article retrieval by using getAllVisibleItems() to reduce unnecessary queries

BP-4012-Performance-update-for-missing-index-in-the-database

---

Model/ConfigProvider/Idin.php
etc/di.xml

update: add support for IDIN payment method in di.xml and implement active status check in Idin.php

BP-4427-IDIN-is-not-working-properly

---

view/frontend/web/css/styles.css
view/frontend/web/js/view/payment/method-renderer/creditcards.js
view/frontend/web/template/payment/buckaroo_magento2_creditcards.html

update: enhance hosted fields reset functionality and improve error handling in credit card processing

BP-4432-UI-Issues-on-Checkout-Credit-Debit-Cards-Hosted-Fields

---

Service/ExpressPayment/ProductValidationService.php
view/adminhtml/templates/credentials_checker.phtml
view/adminhtml/web/js/view/adminhtml/credentials-checker.js

update: enhance credentials checker with configurable element and improved error handling

BP-4447-Test-Credentials-not-working-in-admin-panel

---

Controller/Redirect/Process.php
Observer/RestoreQuote.php
view/frontend/web/js/view/payment/method-renderer/creditcards.js

update: enhance quote restoration logic to handle canceled payments and improve error logging

BP-4458-Klarna-s-canceled-payments-redirect-me-to-an-error-page

---

Model/Push.php

implement invoice creation for capture transactions in Push.php

BP-4524-Capture-from-Plaza-not-working-for-Credit-Cards

---

Model/ConfigProvider/Method/Creditcards.php
etc/adminhtml/system/payment_methods/creditcards.xml
view/frontend/web/js/view/payment/method-renderer/creditcards.js

feat: make hosted fields placeholder text and styling configurable

BP-4576-Make-Hosted-Fields-placeholder-text-configurable

---

Model/ConfigProvider/Method/Paypal.php

refactor: update getPaymentFee method to return default value and improve type hinting

BP-4577-Paypal-percentage-fee-is-calculated-as-fixed-fee

---

Gateway/Command/GatewayCommand.php
Gateway/Request/AdditionalInformation/VATNumberDataBuilder.php
Gateway/Request/Recipient/BillinkDataBuilder.php
view/frontend/web/js/view/payment/method-renderer/billink.js
view/frontend/web/template/payment/buckaroo_magento2_billink.html

feat: add gender validation for Billink payment and improve VAT number handling

BP-4582-Error-when-placing-order-with-Billink

---

Model/Adapter/BuckarooAdapter.php
Model/ConfigProvider/Factory.php
Model/RequestPush/JsonPushRequest.php
Model/Validator/PushSDK.php
Service/Push/OrderRequestService.php

feat: enhance error handling in Buckaroo integration by refining exception management and improving logging

BP-4714-Klarna-KP-push-500-error

---

i18n/de_DE.csv
i18n/en_US.csv
i18n/fr_FR.csv
i18n/nl_NL.csv
view/frontend/web/css/styles.css
view/frontend/web/js/view/payment/method-renderer/creditcards.js
view/frontend/web/template/payment/buckaroo_magento2_creditcards.html

update: add CVC tooltip functionality for credit card input fields

BP-4718-Add-a-tooltip-for-Hosted-Fields-creditcards

---

README.md
Service/Software/Data.php
Setup/Patch/Data/SetupModuleDataPatch.php
composer.json
etc/module.xml

update: bump Buckaroo Magento 2 plugin version to v2.0.1

Bp 4921 update test release 2.0.1

---

Model/Push/DefaultProcessor.php

update: allow invoice processing for authorize payments with shipment-based invoicing

Bp 4925 billink creditcart payments are not captured when order is shipped

---

Gateway/Request/Recipient/AfterpayDataBuilder.php

update: remove hardcoded customer number from Afterpay data builder

BP-5003-Riverty-same-CustomerNumber
